require:
  - rubocop-performance
  - rubocop-rspec

RSpec/MessageChain:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Metricks/BlockNesting:
  Enabled: false

Documentation:
  Enabled: false

AllCops:
  Exclude:
  - 'bin/'
  - '*.gemspec'
  TargetRubyVersion: 2.6.3-v