require:
  - rubocop-performance
  - rubocop-rspec

RSpec/MessageChain:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Metricks/BlockNesting:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 220

Documentation:
  Enabled: false

AllCops:
  Exclude:
  - 'bin/'
  - '*.gemspec'
  - 'spec/**/*'
  TargetRubyVersion: 2.6.3-v